### PR TITLE
Typescript client

### PR DESCRIPTION
**Pull request by khaIilnafis**

### CODE REVIEW

**Review by tracy-codes — CHANGES_REQUESTED** [review]
Need to resolve conflicts in order to merge, please check into this

**Comment by khaIilnafis** [comment]
once the new sdk version is rolled out i'll update the version referenced here and resolve the conflict

**Comment by tracy-codes** [comment]
> once the new sdk version is rolled out i'll update the version referenced here and resolve the conflict

New SDK is now out, 5.0.0 is the new version.

**Review by tracy-codes — APPROVED** [review]
lgtm

**Review by tracy-codes — APPROVED** [review]

**Pull request merged**
